

const state = {
    company1: {
        companyName: '',
        startMonth: '',
        startYear: '',
        endMonth: '',
        endYear: '',
        location: '',
        title1: '',
        task1A: '', task1B: '', task1C: '', task1D: '', task1E: '', task1F: '',
        title2: '',
        task2A: '', task2B: '', task2C: '', task2D: '', task2E: '', task2F: '',
        title3: '',
        task3A: '', task3B: '', task3C: '', task3D: '', task3E: '', task3F: '',
    },
    company2: {
        companyName: '',
        startMonth: '',
        startYear: '',
        endMonth: '',
        endYear: '',
        location: '',
        title1: '',
        task1A: '', task1B: '', task1C: '', task1D: '', task1E: '', task1F: '',
        title2: '',
        task2A: '', task2B: '', task2C: '', task2D: '', task2E: '', task2F: '',
        title3: '',
        task3A: '', task3B: '', task3C: '', task3D: '', task3E: '', task3F: '',
    },
    company3: {
        companyName: '',
        startMonth: '',
        startYear: '',
        endMonth: '',
        endYear: '',
        location: '',
        title1: '',
        task1A: '', task1B: '', task1C: '', task1D: '', task1E: '', task1F: '',
        title2: '',
        task2A: '', task2B: '', task2C: '', task2D: '', task2E: '', task2F: '',
        title3: '',
        task3A: '', task3B: '', task3C: '', task3D: '', task3E: '', task3F: '',
    },
    company4: {
        companyName: '',
        startMonth: '',
        startYear: '',
        endMonth: '',
        endYear: '',
        location: '',
        title1: '',
        task1A: '', task1B: '', task1C: '', task1D: '', task1E: '', task1F: '',
        title2: '',
        task2A: '', task2B: '', task2C: '', task2D: '', task2E: '', task2F: '',
        title3: '',
        task3A: '', task3B: '', task3C: '', task3D: '', task3E: '', task3F: '',
    },
    company5: {
        companyName: '',
        startMonth: '',
        startYear: '',
        endMonth: '',
        endYear: '',
        location: '',
        title1: '',
        task1A: '', task1B: '', task1C: '', task1D: '', task1E: '', task1F: '',
        title2: '',
        task2A: '', task2B: '', task2C: '', task2D: '', task2E: '', task2F: '',
        title3: '',
        task3A: '', task3B: '', task3C: '', task3D: '', task3E: '', task3F: '',
    }
};

const mutations = {
    //Company 1
    updateCompanyName1(state, companyName) { state.company1.companyName = companyName; },
    updateCompanyStartMonth1(state, startMonth) { state.company1.startMonth = startMonth; },
    updateCompanyStartYear1(state, startYear) { state.company1.startYear = startYear; },
    updateCompanyEndMonth1(state, endMonth) { state.company1.endMonth = endMonth; },
    updateCompanyEndYear1(state, endYear) { state.company1.endYear = endYear; },
    updateCompanyLocation1(state, location) { state.company1.location = location; },
    updateCompanyTitle1_1(state, title) { state.company1.title1 = title; },
    updateCompanyTask1A_1(state, task) { state.company1.task1A = task; },
    updateCompanyTask1B_1(state, task) { state.company1.task1B = task; },
    updateCompanyTask1C_1(state, task) { state.company1.task1C = task; },
    updateCompanyTask1D_1(state, task) { state.company1.task1D = task; },
    updateCompanyTask1E_1(state, task) { state.company1.task1E = task; },
    updateCompanyTask1F_1(state, task) { state.company1.task1F = task; },
    updateCompanyTitle2_1(state, title) { state.company1.title2 = title; },
    updateCompanyTask2A_1(state, task) { state.company1.task2A = task; },
    updateCompanyTask2B_1(state, task) { state.company1.task2B = task; },
    updateCompanyTask2C_1(state, task) { state.company1.task2C = task; },
    updateCompanyTask2D_1(state, task) { state.company1.task2D = task; },
    updateCompanyTask2E_1(state, task) { state.company1.task2E = task; },
    updateCompanyTask2F_1(state, task) { state.company1.task2F = task; },
    updateCompanyTitle3_1(state, title) { state.company1.title3 = title; },
    updateCompanyTask3A_1(state, task) { state.company1.task3A = task; },
    updateCompanyTask3B_1(state, task) { state.company1.task3B = task; },
    updateCompanyTask3C_1(state, task) { state.company1.task3C = task; },
    updateCompanyTask3D_1(state, task) { state.company1.task3D = task; },
    updateCompanyTask3E_1(state, task) { state.company1.task3E = task; },
    updateCompanyTask3F_1(state, task) { state.company1.task3F = task; },
    //Company 2
    updateCompanyName2(state, companyName) { state.company2.companyName = companyName; },
    updateCompanyStartMonth2(state, startMonth) { state.company2.startMonth = startMonth; },
    updateCompanyStartYear2(state, startYear) { state.company2.startYear = startYear; },
    updateCompanyEndMonth2(state, endMonth) { state.company2.endMonth = endMonth; },
    updateCompanyEndYear2(state, endYear) { state.company2.endYear = endYear; },
    updateCompanyLocation2(state, location) { state.company2.location = location; },
    updateCompanyTitle1_2(state, title) { state.company2.title1 = title; },
    updateCompanyTask1A_2(state, task) { state.company2.task1A = task; },
    updateCompanyTask1B_2(state, task) { state.company2.task1B = task; },
    updateCompanyTask1C_2(state, task) { state.company2.task1C = task; },
    updateCompanyTask1D_2(state, task) { state.company2.task1D = task; },
    updateCompanyTask1E_2(state, task) { state.company2.task1E = task; },
    updateCompanyTask1F_2(state, task) { state.company2.task1F = task; },
    updateCompanyTitle2_2(state, title) { state.company2.title2 = title; },
    updateCompanyTask2A_2(state, task) { state.company2.task2A = task; },
    updateCompanyTask2B_2(state, task) { state.company2.task2B = task; },
    updateCompanyTask2C_2(state, task) { state.company2.task2C = task; },
    updateCompanyTask2D_2(state, task) { state.company2.task2D = task; },
    updateCompanyTask2E_2(state, task) { state.company2.task2E = task; },
    updateCompanyTask2F_2(state, task) { state.company2.task2F = task; },
    updateCompanyTitle3_2(state, title) { state.company2.title3 = title; },
    updateCompanyTask3A_2(state, task) { state.company2.task3A = task; },
    updateCompanyTask3B_2(state, task) { state.company2.task3B = task; },
    updateCompanyTask3C_2(state, task) { state.company2.task3C = task; },
    updateCompanyTask3D_2(state, task) { state.company2.task3D = task; },
    updateCompanyTask3E_2(state, task) { state.company2.task3E = task; },
    updateCompanyTask3F_2(state, task) { state.company2.task3F = task; },
    //Company 3
    updateCompanyName3(state, companyName) { state.company3.companyName = companyName; },
    updateCompanyStartMonth3(state, startMonth) { state.company3.startMonth = startMonth; },
    updateCompanyStartYear3(state, startYear) { state.company3.startYear = startYear; },
    updateCompanyEndMonth3(state, endMonth) { state.company3.endMonth = endMonth; },
    updateCompanyEndYear3(state, endYear) { state.company3.endYear = endYear; },
    updateCompanyLocation3(state, location) { state.company3.location = location; },
    updateCompanyTitle1_3(state, title) { state.company3.title1 = title; },
    updateCompanyTask1A_3(state, task) { state.company3.task1A = task; },
    updateCompanyTask1B_3(state, task) { state.company3.task1B = task; },
    updateCompanyTask1C_3(state, task) { state.company3.task1C = task; },
    updateCompanyTask1D_3(state, task) { state.company3.task1D = task; },
    updateCompanyTask1E_3(state, task) { state.company3.task1E = task; },
    updateCompanyTask1F_3(state, task) { state.company3.task1F = task; },
    updateCompanyTitle2_3(state, title) { state.company3.title2 = title; },
    updateCompanyTask2A_3(state, task) { state.company3.task2A = task; },
    updateCompanyTask2B_3(state, task) { state.company3.task2B = task; },
    updateCompanyTask2C_3(state, task) { state.company3.task2C = task; },
    updateCompanyTask2D_3(state, task) { state.company3.task2D = task; },
    updateCompanyTask2E_3(state, task) { state.company3.task2E = task; },
    updateCompanyTask2F_3(state, task) { state.company3.task2F = task; },
    updateCompanyTitle3_3(state, title) { state.company3.title3 = title; },
    updateCompanyTask3A_3(state, task) { state.company3.task3A = task; },
    updateCompanyTask3B_3(state, task) { state.company3.task3B = task; },
    updateCompanyTask3C_3(state, task) { state.company3.task3C = task; },
    updateCompanyTask3D_3(state, task) { state.company3.task3D = task; },
    updateCompanyTask3E_3(state, task) { state.company3.task3E = task; },
    updateCompanyTask3F_3(state, task) { state.company3.task3F = task; },
    //Company 4
    updateCompanyName4(state, companyName) { state.company4.companyName = companyName; },
    updateCompanyStartMonth4(state, startMonth) { state.company4.startMonth = startMonth; },
    updateCompanyStartYear4(state, startMonth) { state.company4.startMonth = startMonth; },
    updateCompanyEndMonth4(state, endMonth) { state.company4.endMonth = endMonth; },
    updateCompanyEndYear4(state, endYear) { state.company4.endYear = endYear; },
    updateCompanyLocation4(state, location) { state.company4.location = location; },
    updateCompanyTitle1_4(state, title) { state.company4.title1 = title; },
    updateCompanyTask1A_4(state, task) { state.company4.task1A = task; },
    updateCompanyTask1B_4(state, task) { state.company4.task1B = task; },
    updateCompanyTask1C_4(state, task) { state.company4.task1C = task; },
    updateCompanyTask1D_4(state, task) { state.company4.task1D = task; },
    updateCompanyTask1E_4(state, task) { state.company4.task1E = task; },
    updateCompanyTask1F_4(state, task) { state.company4.task1F = task; },
    updateCompanyTitle2_4(state, title) { state.company4.title2 = title; },
    updateCompanyTask2A_4(state, task) { state.company4.task2A = task; },
    updateCompanyTask2B_4(state, task) { state.company4.task2B = task; },
    updateCompanyTask2C_4(state, task) { state.company4.task2C = task; },
    updateCompanyTask2D_4(state, task) { state.company4.task2D = task; },
    updateCompanyTask2E_4(state, task) { state.company4.task2E = task; },
    updateCompanyTask2F_4(state, task) { state.company4.task2F = task; },
    updateCompanyTitle3_4(state, title) { state.company4.title3 = title; },
    updateCompanyTask3A_4(state, task) { state.company4.task3A = task; },
    updateCompanyTask3B_4(state, task) { state.company4.task3B = task; },
    updateCompanyTask3C_4(state, task) { state.company4.task3C = task; },
    updateCompanyTask3D_4(state, task) { state.company4.task3D = task; },
    updateCompanyTask3E_4(state, task) { state.company4.task3E = task; },
    updateCompanyTask3F_4(state, task) { state.company4.task3F = task; },
    //Company 5
    updateCompanyName5(state, companyName) { state.company5.companyName = companyName; },
    updateCompanyStartMonth5(state, startMonth) { state.company5.startMonth = startMonth; },
    updateCompanyStartYear5(state, startMonth) { state.company5.startMonth = startMonth; },
    updateCompanyEndMonth5(state, endMonth) { state.company5.endMonth = endMonth; },
    updateCompanyEndYear5(state, endYear) { state.company5.endYear = endYear; },
    updateCompanyLocation5(state, location) { state.company5.location = location; },
    updateCompanyTitle1_5(state, title) { state.company5.title1 = title; },
    updateCompanyTask1A_5(state, task) { state.company5.task1A = task; },
    updateCompanyTask1B_5(state, task) { state.company5.task1B = task; },
    updateCompanyTask1C_5(state, task) { state.company5.task1C = task; },
    updateCompanyTask1D_5(state, task) { state.company5.task1D = task; },
    updateCompanyTask1E_5(state, task) { state.company5.task1E = task; },
    updateCompanyTask1F_5(state, task) { state.company5.task1F = task; },
    updateCompanyTitle2_5(state, title) { state.company5.title2 = title; },
    updateCompanyTask2A_5(state, task) { state.company5.task2A = task; },
    updateCompanyTask2B_5(state, task) { state.company5.task2B = task; },
    updateCompanyTask2C_5(state, task) { state.company5.task2C = task; },
    updateCompanyTask2D_5(state, task) { state.company5.task2D = task; },
    updateCompanyTask2E_5(state, task) { state.company5.task2E = task; },
    updateCompanyTask2F_5(state, task) { state.company5.task2F = task; },
    updateCompanyTitle3_5(state, title) { state.company5.title3 = title; },
    updateCompanyTask3A_5(state, task) { state.company5.task3A = task; },
    updateCompanyTask3B_5(state, task) { state.company5.task3B = task; },
    updateCompanyTask3C_5(state, task) { state.company5.task3C = task; },
    updateCompanyTask3D_5(state, task) { state.company5.task3D = task; },
    updateCompanyTask3E_5(state, task) { state.company5.task3E = task; },
    updateCompanyTask3F_5(state, task) { state.company5.task3F = task; },
};

export default {
    state,
    mutations
};